/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppInput: typeof import('./src/components/app/AppInput.vue')['default']
    AppToast: typeof import('./src/components/app/AppToast.vue')['default']
    HomeLatestSong: typeof import('./src/components/HomeLatestSong.vue')['default']
    HomeRecommendation: typeof import('./src/components/HomeRecommendation.vue')['default']
    HomeSwiper: typeof import('./src/components/HomeSwiper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopDragBar: typeof import('./src/components/TopDragBar.vue')['default']
  }
}
